theme = "catppuccin_latte"

[editor]
auto-save = true
rulers = [80, 120]
cursorline = true
cursorcolumn = true
bufferline = "always"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)
### 

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
